/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package PcQnA;

/**
 *
 * @author kq635
 *
 * please note that some parts of sentences of text file is generated by gpt and
 * some has been edited by me
 */
public class main {

    public static void main(String[] args) {
        // Create and start the control system for managing PC components
        Control control = new Control();
        control.start();
    }
}
